name: md-pl

services:
  app:
    build: 
      context: ../..
      dockerfile: deploy/docker/app/Dockerfile
    container_name: md-pl-app
    depends_on:
      - redis-storage
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    labels:
      - "app-identity=magic-delivery"
      - "app-service=md-pl-app"
    networks:
      - public
      - redis
    ports:
      - "8081:8081/tcp"
    read_only: true
    restart: unless-stopped

  redis-storage:
    container_name: md-pl-redis-storage
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    image: redis
    labels:
      - "app-identity=magic-delivery"
      - "app-service=md-pl-redis-storage"
    networks:
      - redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./redis-storage/redis.conf:/usr/local/etc/redis/redis.conf

  redis-populator:
    container_name: md-pl-redis-populator
    depends_on:
      - redis-storage
    entrypoint: ["bash", "/redis-populator/populate.sh", "/redis-populator/data.txt"]
    env_file:
      - ./.env
    image: redis
    labels:
      - "app-identity=magic-delivery"
      - "app-service=md-pl-redis-populator"
    networks:
      - redis
    volumes:
      - ./redis-populator:/redis-populator

#  redis-backup:
#    image: bash
#    entrypoint: ["/snapshot-backup.sh"]
#    depends_on:
#      - redis-storage
#    environment:
#      - BACKUP_PERIOD=60
#    volumes:
#      - ./redis-backup/snapshot-backup.sh:/snapshot-backup.sh
#      - redis-data:/data:ro
#      - backup:/backup
#
volumes:
  redis-data:
    labels:
      - "app-identity=magic-delivery"
      - "app-volume=md-pl-redis-data"
#  backup:
#    labels:
#      - "app-identity=magic-delivery"
#      - "app-volume=pl-backup"

networks:
  public:
    name: md-pl-public
    labels:
      - "app-identity=magic-delivery"
      - "app-network=md-pl-public"
  redis:
    name: md-pl-redis
    labels:
      - "app-identity=magic-delivery"
      - "app-network=md-pl-redis"
