name: verify.yml
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install toolchain
        # Install the stable Rust toolchain with a minimal profile.
        run: rustup toolchain install stable --profile minimal

      - name: cache dependencies
        # Cache dependencies to speed up builds using rust-cache.
        uses: Swatinem/rust-cache@v2

      - name: cargo test
        # Run all tests with cargo test to ensure code correctness.
        run: cargo test --all-features

      - name: rustfmt
        # Check code formatting using cargo fmt to enforce style consistency.
        run: cargo fmt --all -- --check

      - name: clippy
        # Use cargo clippy to perform linting and enforce warnings as errors.
        run: cargo clippy --all --all-features --tests -- -D warnings
